### ISSUE TITLE
Patch release

### ISSUE THREAD

**Issue by Nukesor** [andre-vm/rev_buf_reader#5]
Hey @andre-vm :)

I just wanted to ask, if you could publish a patch release in the near future.

I'm planning to publish a new release candidate and I would really like to have the changes of https://github.com/andre-vm/rev_buf_reader/pull/2 in there :D

Best regards,

Arne

**Comment by andre-vm** [comment]
Hey @Nukesor! Sorry for the delay!
Yes, I can publish a new release this weekend. 👍 
I'd also like to update the code to match the recent changes in the standard lib before publishing the new version.
I'll keep you posted in this thread.

**Comment by andre-vm** [comment]
There we have it! [0.3.0](https://github.com/andre-vm/rev_buf_reader/releases/tag/0.3.0)
I still wasn't able to get the code up to speed with the latest changes to the std lib, I'll try to bring more of those changes to this lib, but at least now we have a published version that doesn't panick on IO errors.
@Nukesor Please let me know if you have any issues. As always, feel free to open new PRs, and I'll get your changes published in a hotfix, if needed.

**Comment by Nukesor** [comment]
Awesome! Thanks for your work and swift response :)
